# Generated by Django 4.2.7 on 2024-01-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bazar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="data_fim",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_inicio",
            field=models.DateField(),
        ),
    ]
