# Generated by Django 4.2.7 on 2024-01-08 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bazar", "0002_alter_evento_poster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="ativo",
        ),
    ]
