# Generated by Django 4.2.7 on 2024-01-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bazar", "0003_remove_evento_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="preco",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
